import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { data1, data2, data3, data4, data5, data6, data7, data8, data9, data11, data12, data13, data14, data15, data16, data17, data18, data19 } from "@/components/large-data";

const inter = Inter({ subsets: ["latin"] });

export const config = {
  runtime: 'experimental-edge'
};

export default function LargePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>This page imports a very large dependency.</p>
          {/* let's make sure data isn't tree-shakeable */}
          <p>{data1.length + data2.length + data3.length + data4.length + data5.length + data6.length + data7.length + data8.length + data9.length + data11.length + data12.length + data13.length + data14.length + data15.length + data16.length + data17.length + data18.length + data19.length} bytes</p>
        </div>
      </main>
    </>
  );
}